# Global Configuration Settings
kafka_bootstrap_servers: "kafka:9092"
kafka_group_id: "syslog-consumers"
kafka_max_records_poll: 500
batch_size: 30000

# Handler Configuration
handler:
  type: "NFWareSyslogHandler"
  options: {}

# Outputs Configuration
outputs:
  # TimeScaleDB Output
  - type: "TimeScaleDBOutput"
    options:
      address: "tsdb"
      port: 5432
      username: "cgnat"
      password: "password123"
      database: "cgnat"
      batch_size: 30000

  # Example Kafka Output   # Possible values: x_ip, x_port, dst_ip, dst_port, src_ip, src_port
  # - type: "KafkaOutput"
  #   options:
  #     bootstrap_servers: "localhost:9094"
  #     topic: "cgnat.events"
  #     key_field: "x_ip"
  #     topic_event_map:
  #       session-mapping: "sometopic.for.sessionmapping"
  #       address-mapping: "sometopic.for.addressmapping"
  #     producer_extra_config: {}

  # Example Redis Output  # src_ip is typically the best key_field for 99% of scenarios
  # - type: "RedisOutput"
  #   options:
  #     host: redis
  #     port: 6379
  #     key_field: src_ip

  # Example HTTP Output
  # - type: "HTTPWebhookOutput"
  #   options:
  #     url: "http://webhook/metrics"
  #     headers:
  #       x-api-key: default-change-me
  #     timeout: 10
  #   preprocessors:
  #     - name: filter_keys
  #       arguments:
  #         keys:
  #           - src_ip
  #           - src_port
  #           - x_ip
  #           - x_port
  #           - timestamp
  #           - dst_ip
  #           - dst_port
  #           - event
  #     - name: match_kvs
  #       arguments:
  #         kvs:
  #           src_ip: 192.168.3.30
  #     - name: key_exists
  #       arguments:
  #         key: dst_port
  #         ignore_none: true