services:
  radius_collector:
    image: veesixnetworks/cgn-ec-producer-radius:v1.0.1
    ports:
      - 1813:1813/udp
    networks:
      - kafka
    profiles: [radius]
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  syslog_collector:
    image: balabit/syslog-ng:4.8.0
    ports:
      - 1514:1514/udp
    networks:
      - kafka
    volumes:
      - "./producer/syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      - "./producer/syslog/cgn-ec.conf.d:/etc/syslog-ng/cgn-ec.conf.d"
    profiles: [syslog]

  netflow_collector:
    image: pmacct/nfacctd:bleeding-edge
    init: true
    ports:
      - 9995:9995/udp
    networks:
      - kafka
    volumes:
      - ./producer/netflow/nfacctd.conf:/etc/pmacct/nfacctd.conf:ro
      - ./producer/netflow/kafka.conf:/etc/pmacct/kafka.conf:ro
      - ./producer/netflow/data:/root/data
    profiles: [netflow]

  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - 9094:9094
    volumes:
      - kafka_data:/bitnami
    networks:
      - kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'INTERNAL://kafka:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://:9094'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_KRAFT_CLUSTER_ID: 'fiWo7IWazngRchmPES6qcA=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka_ui:
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka

  consumer:
    image: veesixnetworks/cgn-ec-consumer:v0.5.0
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_RECORDS_POLL: 30000
    networks:
      - kafka
      - cgn_ec

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - cgn_ec
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - 3000:3000
    container_name: grafana
    networks:
      - cgn_ec
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    restart: unless-stopped
    command: ["--kafka.server=kafka:9092"]
    networks:
      - kafka
      - cgn_ec
    ports:
      - 9308:9308

  api:
    image: veesixnetworks/cgn-ec-api:v0.2.1
    ports:
      - 3001:80
    networks:
      - cgn_ec
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-tsdb}
      POSTGRES_USER: ${POSTGRES_USER:-cgnat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-cgnat}

  tsdb:
    image: timescale/timescaledb:2.17.2-pg17
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cgnat
      POSTGRES_PASSWORD: password123
    networks:
      - cgn_ec
    profiles: [db]

volumes:
  kafka_data:
    driver: local
  prom_data: {}

networks:
  kafka: {}
  cgn_ec: {}