services:
  radius_collector:
    build:
      context: .
      dockerfile: dockerfiles/freeradius.Dockerfile
    restart: "unless-stopped"
    ports:
      - "1813:1813/udp"
    networks:
      - kafka
    volumes:
      - ./producer/radius/python3/:/cgn_ec_freeradius
      - ./producer/radius/mods-enabled:/etc/raddb/mods-enabled
      - ./producer/radius/sites-enabled:/etc/raddb/sites-enabled
      - ./producer/radius/clients.conf:/etc/raddb/clients.conf
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  syslog_collector:
    image: balabit/syslog-ng:4.8.0
    restart: "unless-stopped"
    ports:
      - "1514:1514/udp"
    networks:
      - kafka
    volumes:
      - "./producer/syslog/:/etc/syslog-ng/"

  netflow_collector:
    image: pmacct/nfacctd:bleeding-edge
    restart: "unless-stopped"
    init: true
    ports:
      - "9995:9995/udp"
    networks:
      - kafka
    volumes:
      - ./producer/netflow/nfacctd.conf:/etc/pmacct/nfacctd.conf:ro
      - ./producer/netflow/data:/root/data

  kafka:
    image: docker.io/bitnami/kafka:3.9
    restart: "unless-stopped"
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://kafka:9094'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_KRAFT_CLUSTER_ID: 'fiWo7IWazngRchmPES6qcA=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      BITNAMI_DEBUG: 'true'

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    restart: "unless-stopped"
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka

  db:
    image: timescale/timescaledb:2.17.2-pg17
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./configs/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cgnat
      POSTGRES_PASSWORD: password123
    networks:
      - cgn_ec

  consumer:
    image: ghcr.io/veesix-networks/cgn-ec-consumer:v0.1.1
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - kafka
      - cgn_ec

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - cgn_ec
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - cgn_ec
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    command:
      - --kafka.server=kafka:9092
    networks:
      - kafka
      - cgn_ec

  api:
    image: ghcr.io/veesix-networks/cgn-ec-api:v0.2.0
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - 3001:80

volumes:
  kafka_data:
    driver: local
  prom_data:

networks:
  kafka: {}
  cgn_ec: {}