site_name: veesix ::networks - cgn-ec
site_url: https://docs.veesix-networks.co.uk/cgn-ec
repo_url: https://github.com/veesix-networks/cgn-ec
repo_name: veesix-networks/cgn-ec
logo: img/logo.png
plugins:
  - redoc-tag
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Get Started: 
    - Intro: index.md
    - Recommended Configuration: recommended_setup.md
    - Compression Examples: compression_examples.md
  - Architecture:
    - General Design: architecture/general_design.md
    - Extra Diagrams: architecture/further_look.md
    - Collectors (Producers): architecture/collectors.md
    - Preprocessors: architecture/preprocessors.md
    - Consumers: architecture/consumers.md
    - Handlers: architecture/handlers.md
    - Outputs: architecture/outputs.md
    - Kafka: architecture/message_queue.md
    - TimescaleDB Models: architecture/timescale_models.md
    - API Hooks: architecture/api_hooks.md
  - API & SDKs: 
    - API: api/index.md
    - Python SDK: api/python_sdk.md
  - Contributing:
    - PLEASE READ FIRST: contributing/please_read_first.md
    - Coding Style: contributing/coding_style.md
    - Tests: contributing/tests.md
  - Author: https://github.com/BSpendlove
markdown_extensions:
  - tables
  - admonition
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences