{
 "title": "CGN-EC Dashboard",
 "description": "CGN-EC metrics",
 "tags": [ "CGN-EC" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cgn_total_metrics_processed,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cgn_total_metrics_processed{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(cgn_process_metrics_total{instance=\"$instance\"},handler_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Metrics Processed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(cgn_total_metrics_processed{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average metrics per second per Process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pid) (cgn_metrics_per_second{job=\"$job\"})",
     "legendFormat": "Process: {{pid}}"
    }
   ]
  },
  {
   "title": "Total Metrics processed by Handlers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler_type) (increase(cgn_process_metrics_total{handler_type=\"$handler\"}[$__rate_interval]))",
     "legendFormat": "{{handler_type}}"
    }
   ]
  },
  {
   "title": "Average time spent processing messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(pid) (cgn_message_processing_seconds{job=\"$job\", handler_type=\"$handler\"})",
     "legendFormat": "Process: {{pid}}"
    }
   ]
  }
 ]
}